### ISSUE TITLE
老哥我发现少包

### ISSUE THREAD

**Issue by lifeizhaopaopao** [maliangnansheng/bbs-springboot#1]
<img width="518" alt="image" src="https://user-images.githubusercontent.com/16394061/178716831-fcb2a310-0adb-4f3a-a478-cf3259fc5bf8.png">
项目跑不起来

**Comment by maliangnansheng** [comment]
临时方案，自己去下载一下：http://chat.nanshengbbs.top/

**Comment by maliangnansheng** [comment]
教程已经更新了，上面的临时方案可以不管（不推荐：如果不想替换settings.xml的童鞋可以使用上面的临时方案）

**Comment by zhou-simon** [comment]
为什么一些公告包 需要放在私服上 然后不得不引入这些

**Comment by maliangnansheng** [comment]
> 为什么一些公告包 需要放在私服上 然后不得不引入这些

使用私库管理maven不是开发友好型嘛，微服务 dubbo之间的调用可以解藕

**Comment by zhou-simon** [comment]
这不是强行绑定了这些服务吗

**Comment by maliangnansheng** [comment]
> 这不是强行绑定了这些服务吗

你觉得应该怎样搞？于自己而言这不是开发更加方便有效嘛？最后上线（到服务器）又不需要管这些（只要打包时能拉到依赖即可）

**Comment by maliangnansheng** [comment]
> 为什么一些公告包 需要放在私服上 然后不得不引入这些

1.节约外网的带宽，一般私服都是搭建在公司内部局域网（我们用的是阿里的云效），用户需要下载依赖时，先去本地查找，本地没有在去私服获取，私服没有，会去配置的中央仓库获取，然后保存在私服上。这样其他用户在去获取的话，就不会在去中央仓库获取，直接可以从私服上获取。

2.项目内的依赖进行统一管理，可以把一些中央仓库没有的第三方依赖，或者是自己项目中的依赖放入私服的私库中，以供其他同事使用

3.加速构建速度，在配置快照时进行构建时，会不停检查远端的数据，如果是访问外网远程仓库会很消耗时间，访问内网私服会大大提高效率
