### ISSUE TITLE
后台管理

### ISSUE THREAD

**Issue by mmengdi** [maliangnansheng/bbs-springboot#13]
1.目前后台管理没有开源吗？
2.项目部署后没有话题功能吗？

**Comment by maliangnansheng** [comment]
> 1.目前后台管理没有开源吗？ 2.项目部署后没有话题功能吗？

可以看看这两篇文章
南生运营的理念：https://bbs.nanshengbbs.top/detail/171
南生论坛日常迭代(开源计划)：https://bbs.nanshengbbs.top/detail/122
![image](https://github.com/maliangnansheng/bbs-springboot/assets/13656542/62dd8d59-32f9-40a7-98b4-9539cefe790c)
