### ISSUE TITLE
作者你这不是完全开源，这几个包都没

### ISSUE THREAD

**Issue by rt940910a** [maliangnansheng/bbs-springboot#6]
![image](https://user-images.githubusercontent.com/27659152/217708744-cd3a47a3-0727-4122-9b20-9c4ddb45f452.png)

**Comment by maliangnansheng** [comment]
**同学，没有仔细看教程哈，我教程写的非常详细**
[后端安装教程](http://bbs.nanshengbbs.top/detail/44)
[前端安装教程](http://bbs.nanshengbbs.top/detail/45)

1.替换成作者提供的`settings.xml`
![image.png](http://76.nanshengbbs.top/articlePicture-20230209112353482_image.png)


2.不想替换settings.xml的童鞋自取
http://76.nanshengbbs.top/jar/manage-auth-facade-1.0.0-SNAPSHOT.jar
http://76.nanshengbbs.top/jar/manage-concern-facade-1.0.0-SNAPSHOT.jar
http://76.nanshengbbs.top/jar/nansheng-common-1.0.0-SNAPSHOT.jar
http://76.nanshengbbs.top/jar/nansheng-mybatis-generator-1.0.0-SNAPSHOT.jar
